#!bin/bash

#/ ################################################################################## /#
#                                                                                      #
#                                                                                      #
#           ファイル名：  ora_UItool            ( Oracle SELECTツール )                  #
#                                                                                      #
#                                                                                      #
#           引数： ora_UItool (void)                                                    #
#                                                                                      #
#           使用方法：shにて起動し、表示される番号によって遷移する                          #
#                    自ファイルにてsqlファイルを作成し、                                  #
#                    CUIにてユーザーからの値によりSQLファイルに書き込む                    #
#                    ora_Viewtool.cppを起動し作成したSQLファイをを読み込む                #
#                                                                                      #
#           注意：本プロセスはselect文のみ使用可とし、それ以外の入力は拒否する               #
#                                                                                      #
#/ ################################################################################### /#



#/ ################################################################################## /#
#                                                                                      #
#                                                                                      #
#           関数名：  directSP_EXE                 ( 直接入力SQL )                       #
#                                                                                      #
#                                                                                      #
#           引数： directSP_EXE (void)                                                  #
#                                                                                      #
#           使用方法：UIにて直接入力されたSQLをチェックし、SQLファイルに記述                #
#                    SQLファイルを自プロセス内にて作成                                    #
#                    ora_Viewtool.cppを起動しする                                       #
#                                                                                      #
#                                                                                      #
#/ ################################################################################### /#

function directSP_EXE(){

    sfName="./r.sql"

    # sqlファイル作成
    touch "$sfName"

    # 入力プロセス
    while :
    do
        echo  -n "SQL> "  
        read sql

        if [[ "${sql}" =~ "quit" ]]; then
            echo "コマンド:[quit] 終了"
            break
        fi

        if [[ "${sql}" =~ "select" ]] || [[ "${sql}" =~ "SELECT" ]]; then
            echo "$sql" > "$sfName"

        else
            echo "selectが記述されていません"
            continue
        fi
        
        #SQL複数段対応
        index_s=2
        while :
        do
        echo -n "  ${index_s}  "
        read sql

        # 空白の場合SQLリセット
        if [ -z "$sql" ]; then
            break
        fi

        echo "$sql" >> "$sfName"

        if [[ "${sql}" =~ ";" ]]; then
            break
        else
            index_s=$(($index_s + 1))
        fi

        done

        # SQL*Plus実行
        #$sts=./ora_UItool ${shName}

        # 戻り値(err)は再度
        if [ sts != 0 ]; then
            continue
        fi

    done
}

#/ ################################################################################## /#
#                                                                                      #
#                                                                                      #
#           関数名：  main                  ( SELECTツール )                            #
#                                                                                      #
#                                                                                      #
#           引数： main (void)                                                          #
#                                                                                      #
#           使用方法：UIにて入力された番号により処理を遷移                                 #
#                                                                                      #
#                                                                                      #
#/ ################################################################################### /#


# 終了コマンドが押されるまで
while :

do
    # 処理分岐プロセス
    echo "****************************************"
    echo "*    oraTool (Oracle SELECTツール)     *"
    echo "*                                      *"
    echo "*      0: 直接入力                     *"
    echo "*      1:                              *"
    echo "*      e: 終了                         *"
    echo "*                                      *"
    echo "****************************************"
    echo -n "番号を入力してください: "
    read INDEX

    #入力された値によって処理分岐
    if [ ${INDEX} == 0 ]; then
    #関数：direct
    'directSP_EXE'

    # elif [ ${INDEX} == 1 ]; then
    # 関数：none

    elif [ ${INDEX}=='e' ]; then
        # ツール終了
        break

    else
        #再度入力実施
        echo "入力された値に誤りがあります\n"
        echo "再度入力してください\n"
        continue

    fi

# 処理分岐プロセスend
done
